//V2 IB

#define LED_SYS_ON()  	{GPIO_BOP(GPIOB)=GPIO_PIN_1;}
#define LED_SYS_OFF() 	{GPIO_BC (GPIOB)=GPIO_PIN_1;}

#define HMDT_ON()       {GPIO_BOP(GPIOA)=GPIO_PIN_8;}
#define HMDT_OFF()      {GPIO_BC (GPIOA)=GPIO_PIN_8;}
#define HMDT_ON_Bit			gpio_input_bit_get(GPIOA,GPIO_PIN_8)
#define SENS_T_ON()     {GPIO_BOP(GPIOC)=GPIO_PIN_13;}
#define SENS_T_OFF()    {GPIO_BC(GPIOC)=GPIO_PIN_13;}
#define HEAT1_ON()      {GPIO_BC(GPIOC)=GPIO_PIN_10;}
#define HEAT1_OFF()     {GPIO_BOP(GPIOC)=GPIO_PIN_10;}
#define HEAT1_Bit    		gpio_input_bit_get(GPIOC,GPIO_PIN_10)
#define HEAT2_ON()      {GPIO_BC(GPIOC)=GPIO_PIN_11;}
#define HEAT2_OFF()     {GPIO_BOP(GPIOC)=GPIO_PIN_11;}
#define HEAT2_Bit    		gpio_input_bit_get(GPIOC,GPIO_PIN_11)
#define HEAT_ALL_ON()   {GPIO_BC(GPIOC)=GPIO_PIN_12;}
#define HEAT_ALL_OFF()  {GPIO_BOP(GPIOC)=GPIO_PIN_12;}
#define HEAT_ALL_Bit    gpio_input_bit_get(GPIOC,GPIO_PIN_12)
#define Heater_Boost_On()  {GPIO_BOP(GPIOC)=GPIO_PIN_14;}
#define Heater_Boost_Off() {GPIO_BC (GPIOC)=GPIO_PIN_14;}
#define Heater_Boost_Bit   gpio_input_bit_get(GPIOC,GPIO_PIN_14)

#define Screen_Pwr_On() {GPIO_BOP(GPIOB)=GPIO_PIN_9;}
#define Screen_Pwr_Of()	{GPIO_BC (GPIOB)=GPIO_PIN_9;}
#define Screen_Pwr_Bit	gpio_input_bit_get(GPIOB,GPIO_PIN_9)

#define ValvePwr_On()   {GPIO_BC (GPIOA)=GPIO_PIN_1;}
#define ValvePwr_Off()  {GPIO_BOP(GPIOA)=GPIO_PIN_1;}
#define ValvePwr_Bit		gpio_input_bit_get(GPIOA,GPIO_PIN_1)
#define Valve_On()    	{GPIO_BC (GPIOA)=GPIO_PIN_4;}
#define Valve_Off()   	{GPIO_BOP(GPIOA)=GPIO_PIN_4;}
#define VENT_ON() 			{GPIO_BC (GPIOA)=GPIO_PIN_7;}
#define VENT_OFF() 			{GPIO_BOP(GPIOA)=GPIO_PIN_7;}
#define VENT_ON_Bit			gpio_input_bit_get(GPIOA,GPIO_PIN_7)

#define ADC_CS_UP() {GPIO_BOP(GPIOC)=GPIO_PIN_2;}
#define ADC_CS_DN() {GPIO_BC(GPIOC)=GPIO_PIN_2;}
#define ADC_CLK_UP() {GPIO_BOP(GPIOC)=GPIO_PIN_0;}
#define ADC_CLK_DN() {GPIO_BC(GPIOC)=GPIO_PIN_0;}
// DWN
/*
#define KEY_DWN0_ON()  {GPIO_BOP(GPIOB)=GPIO_PIN_11;}
#define KEY_DWN0_OFF() {GPIO_BC(GPIOB)=GPIO_PIN_11;}
#define KEY_DWN1_ON()  {GPIO_BOP(GPIOB)=GPIO_PIN_10;}
#define KEY_DWN1_OFF() {GPIO_BC(GPIOB)=GPIO_PIN_10;}
*/

#define KEY_DWN0_ON()  {GPIO_BOP(GPIOA)=GPIO_PIN_12;}
#define KEY_DWN0_OFF() {GPIO_BC(GPIOA)=GPIO_PIN_12;}
#define KEY_DWN1_ON()  {GPIO_BOP(GPIOA)=GPIO_PIN_11;}
#define KEY_DWN1_OFF() {GPIO_BC(GPIOA)=GPIO_PIN_11;}

#define KEY_DWN2_ON()  {GPIO_BOP(GPIOB)=GPIO_PIN_5;}
#define KEY_DWN2_OFF() {GPIO_BC(GPIOB)=GPIO_PIN_5;}
#define KEY_DWN3_ON()  {GPIO_BOP(GPIOB)=GPIO_PIN_6;}
#define KEY_DWN3_OFF() {GPIO_BC(GPIOB)=GPIO_PIN_6;}
#define KEY_DWN4_ON()  {GPIO_BOP(GPIOB)=GPIO_PIN_7;}
#define KEY_DWN4_OFF() {GPIO_BC(GPIOB)=GPIO_PIN_7;}
#define KEY_DWN5_ON()  {GPIO_BOP(GPIOB)=GPIO_PIN_8;}
#define KEY_DWN5_OFF() {GPIO_BC(GPIOB)=GPIO_PIN_8;}
// UP
#define KEY_UP0_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_6;}
#define KEY_UP0_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_6;}
#define KEY_UP1_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_5;}
#define KEY_UP1_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_5;}
#define KEY_UP2_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_4;}
#define KEY_UP2_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_4;}
#define KEY_UP3_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_3;}
#define KEY_UP3_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_3;}
#define KEY_UP4_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_2;}
#define KEY_UP4_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_2;}	
#define KEY_UP5_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_1;}
#define KEY_UP5_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_1;}
#define KEY_UP6_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_0;}
#define KEY_UP6_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_0;}	
#define KEY_UP7_ON()  {GPIO_BOP(GPIOC)=GPIO_PIN_9;}
#define KEY_UP7_OFF() {GPIO_BC(GPIOC)=GPIO_PIN_9;}	
#define KEY_UP8_ON()  {GPIO_BOP(GPIOC)=GPIO_PIN_8;}
#define KEY_UP8_OFF() {GPIO_BC(GPIOC)=GPIO_PIN_8;}	
#define KEY_UP9_ON()  {GPIO_BOP(GPIOC)=GPIO_PIN_7;}
#define KEY_UP9_OFF() {GPIO_BC(GPIOC)=GPIO_PIN_7;}	
#define KEY_UP10_ON()  {GPIO_BOP(GPIOC)=GPIO_PIN_6;}
#define KEY_UP10_OFF() {GPIO_BC(GPIOC)=GPIO_PIN_6;}	
#define KEY_UP11_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_15;}
#define KEY_UP11_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_15;}
#define KEY_UP12_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_10;}
#define KEY_UP12_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_10;}
#define KEY_UP13_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_9;}
#define KEY_UP13_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_9;}
#define KEY_UP14_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_8;}
#define KEY_UP14_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_8;}
#define KEY_UP15_ON()  {GPIO_BOP(GPIOB)=GPIO_PIN_15;}
#define KEY_UP15_OFF() {GPIO_BC(GPIOB)=GPIO_PIN_15;}
#define KEY_UP16_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_14;}
#define KEY_UP16_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_14;}
#define KEY_UP17_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_13;}
#define KEY_UP17_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_13;}
#define KEY_UP18_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_12;}
#define KEY_UP18_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_12;}
#define KEY_UP19_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_11;}
#define KEY_UP19_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_11;}
// MID
#define KEY_MID0_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_7;}
#define KEY_MID0_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_7;}
#define KEY_MID1_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_8;}
#define KEY_MID1_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_8;}
#define KEY_MID2_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_9;}
#define KEY_MID2_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_9;}
#define KEY_MID3_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_10;}
#define KEY_MID3_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_10;}
#define KEY_MID4_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_15;}
#define KEY_MID4_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_15;}
#define KEY_MID5_ON()  {GPIO_BOP(GPIOB)=GPIO_PIN_12;}
#define KEY_MID5_OFF() {GPIO_BC(GPIOB)=GPIO_PIN_12;}
#define KEY_MID6_ON()  {GPIO_BOP(GPIOB)=GPIO_PIN_13;}
#define KEY_MID6_OFF() {GPIO_BC(GPIOB)=GPIO_PIN_13;}
#define KEY_MID7_ON()  {GPIO_BOP(GPIOB)=GPIO_PIN_14;}
#define KEY_MID7_OFF() {GPIO_BC(GPIOB)=GPIO_PIN_14;}
#define KEY_MID8_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_11;}
#define KEY_MID8_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_11;}
#define KEY_MID9_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_12;}
#define KEY_MID9_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_12;}
#define KEY_MID10_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_13;}
#define KEY_MID10_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_13;}
#define KEY_MID11_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_14;}
#define KEY_MID11_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_14;}
#define KEY_MID12_ON()  {GPIO_BOP(GPIOD)=GPIO_PIN_7;}
#define KEY_MID12_OFF() {GPIO_BC(GPIOD)=GPIO_PIN_7;}
#define KEY_MID13_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_0;}
#define KEY_MID13_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_0;}
#define KEY_MID14_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_1;}
#define KEY_MID14_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_1;}
#define KEY_MID15_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_2;}
#define KEY_MID15_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_2;}
#define KEY_MID16_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_3;}
#define KEY_MID16_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_3;}  
#define KEY_MID17_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_4;}
#define KEY_MID17_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_4;}
#define KEY_MID18_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_5;}
#define KEY_MID18_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_5;}
#define KEY_MID19_ON()  {GPIO_BOP(GPIOE)=GPIO_PIN_6;}
#define KEY_MID19_OFF() {GPIO_BC(GPIOE)=GPIO_PIN_6;}
